import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Load the base API URL from the environment variable
const { VITE_APP_BASE_API_URL } = import.meta.env;

// Create a base query function that will be used for all requests
// This function adds the Authorization header with a Bearer token if available
const baseQuery = fetchBaseQuery({
  baseUrl: VITE_APP_BASE_API_URL,
  prepareHeaders: (headers) => {
    let token = localStorage.getItem('token');

    if (token) {
      // Remove surrounding quotes if they exist
      token = token.replace(/^"(.*)"$/, '$1');
      headers.set('Authorization', `Bearer ${token}`);
    }

    console.log(token);

    // Add CORS-specific headers
    headers.set('Accept', 'application/json');
    headers.set('Content-Type', 'application/json');
    return headers;
  },
});


// Create the API slice using RTK Query
// This defines all the API endpoints your frontend will use
export const apiSlice = createApi({
  reducerPath: 'api', // Unique key to identify this slice in the Redux store
  baseQuery, // Use the baseQuery we defined above
  endpoints: (builder) => ({
    // Endpoint to log in a user
    // Sends a POST request to the backend with login data
    login: builder.mutation({
      query: (data) => ({
        url: 'login',
        method: 'POST',
        body: data,
      }),
    }),

    // Endpoint to log out a user
    // Sends a POST request to the backend with logout 
    logout: builder.mutation({
      query: () => ({
        url: 'logout',
        method: 'POST',
      }),
    }),

    // Endpoint to get the currently logged-in user's info
    // Sends a GET request to /users/me
    getCurrentUser: builder.query({
      query: () => ({
        url: '/user',
        method: 'GET',
      }),
    }),

    // Endpoint to fetch all tickets
    // Useful for displaying a list of tickets
    getTickets: builder.query({
      query: () => ({
        url: '/tickets',
        method: 'GET',
      }),
    }),

    // Endpoint to fetch single ticket
    // Useful for displaying a ticket by id
    getTicket: builder.query({
      query: (id) => ({
        url: `/tickets/${id}`,
        method: 'GET',
      }),
    }),

    // Endpoint to create a new ticket
    // Sends a POST request with the new ticket data
    createTicket: builder.mutation({
      query: (data) => ({
        url: "/tickets",
        method: 'POST',
        body: data,
      }),
    }),

    // Endpoint to update an existing ticket
    // Takes an ID and new data, sends a PUT request
    updateTicket: builder.mutation({
      query: ({id, data}) => {
        return ({
          url: `/tickets/${id}`,
          method: 'PUT',
          body: data,
        });
      }
    }),

    // Endpoint to delete a ticket by ID
    // Sends a DELETE request to remove the ticket
    deleteTicket: builder.mutation({
      query: (id) => ({
        url: `/tickets/${id}`,
        method: 'DELETE',
      }),
    }),

    // Endpoint to create a new ticket
    // Sends a POST request with the new ticket data
    createComment: builder.mutation({
      query: (data) => ({
        url: '/comments',
        method: 'POST',
        body: data,
      }),
    }),

  }),
});

// Export hooks generated by the API slice
// These are used inside React components to call the endpoints
export const {
  useLoginMutation,
  useLogoutMutation,
  useGetCurrentUserQuery,
  useGetTicketsQuery,
  useGetTicketQuery,
  useCreateTicketMutation,
  useUpdateTicketMutation,
  useDeleteTicketMutation,
  useCreateCommentMutation
} = apiSlice;
